### ISSUE TITLE
error GraphQL Error Unknown field `author` on type `frontmatter_2`

### ISSUE THREAD

**Issue by chrisueda** [eggheadio/gatsby-starter-egghead-blog#17]
I deleted the demo folders demo02 to demo09 thinking that I would use add my own posts but got this error:

`error GraphQL Error Unknown field `author` on type `frontmatter_2`

  file: /Users/chrisu/Projects/blog/src/templates/post.js

   1 |
   2 |   query($id: String!) {
   3 |     site {
   4 |       ...site
   5 |     }
   6 |     mdx(fields: { id: { eq: $id } }) {
   7 |       frontmatter {
   8 |         title
   9 |         date(formatString: "MMMM DD, YYYY")
> 10 |         author
     |         ^
  11 |         banner {
  12 |           childImageSharp {
  13 |             fluid(maxWidth: 900) {
  14 |               ...GatsbyImageSharpFluid_withWebp_tracedSVG
  15 |             }
  16 |           }
  17 |         }
  18 |         slug
  19 |         keywords
  20 |       }

ℹ ｢wdm｣: wait until bundle finished: /commons.js
 ERROR  Failed to compile with 1 errors                                                      20:29:22

 error  in ./src/templates/post.js

Module Error (from ./node_modules/eslint-loader/index.js):

/Users/chrisu/Projects/blog/src/templates/post.js
  102:9  error  Cannot query field "author" on type "frontmatter_2"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./.cache/sync-requires.js 16:57-117
 @ ./.cache/app.js
 @ multi (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app

✖ ｢wdm｣:
ERROR in ./src/templates/post.js
Module Error (from ./node_modules/eslint-loader/index.js):

/Users/chrisu/Projects/blog/src/templates/post.js
  102:9  error  Cannot query field "author" on type "frontmatter_2"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./.cache/sync-requires.js 16:57-117
 @ ./.cache/app.js
 @ multi (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
ℹ ｢wdm｣: Failed to compile.`

Deleting the author query in the post.js file gets rid of the error but I'm not sure what the underlying cause is. I wouldn't think deleting the content files would cause it to not compile.

**Comment by vojtaholik** [comment]
`author` has to be defined in frontmatter for post query to run properly, which wasn't the case after deleting demo posts 2—9. 

A workaround is to add `author` to ghost post which fixes it: https://github.com/eggheadio/gatsby-starter-egghead-blog/commit/b5c5ee3519917d94a6db07c14d8ca678c07972b2

thanks for the report @chrisueda 🙏
