### ISSUE TITLE
Example site?

### ISSUE THREAD

**Issue by Caitacular** [eggheadio/gatsby-starter-egghead-blog#2]
Do you perhaps have an example of this starter hosted on Netlify or something? I'm curious what it looks like and being able to see it before setting it up locally is great!

**Comment by pnhoang** [comment]
would be nice to see in the sample how at least thing should be setup. it does not show even after cloning.

**Comment by ekremkenter** [comment]
I just forked and deployed it on Netlify. You can check it out there: [https://nostalgic-swartz-ab79c4.netlify.com/demo-01](https://nostalgic-swartz-ab79c4.netlify.com/demo-01)

**Comment by joelhooks** [comment]
Will add this to the list and get an example up and running on Netlify.

**Comment by joelhooks** [comment]
https://egghead-gatsby-starter.netlify.com/
