### ISSUE TITLE
Syntax highlight doesn't indent code

### ISSUE THREAD

**Issue by neohed** [eggheadio/gatsby-starter-egghead-blog#25]
Hi,
The Code.js component doesn't seem to perform any indentation.  Is this possible via configuration?

I looked at the Formidable Labs page for 'prism-react-renderer' but couldn't see anything there about indentation.

**Comment by vojtaholik** [comment]
Hi @neohed! Thanks for reporting this. I just pushed [a fix](https://github.com/eggheadio/gatsby-starter-egghead-blog/commit/f7a204c691d27b87fa59c5cffc4538b948271efd#diff-7f0c76a2ae5367a17540b4c670e60141L114), should work fine now. 👍

**Comment by neohed** [comment]
Hi @vojtaholik,

Wow that was quick work!  Thank you, I'll give that a try.
